name: CI

on:
  push:
    branches:
      - main

  pull_request:
    paths-ignore:
      - ".vscode/**"
      - "**/*.md"

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request_target' && github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  format:
    if: github.event_name == 'pull_request'
    uses: ./.github/workflows/format.yml
    secrets: inherit
    permissions:
      contents: write
    with:
      ref: ${{ github.head_ref || github.ref }}

  release:
    if: github.event_name == 'push'
    uses: ./.github/workflows/release.yml
    secrets: inherit
    with:
      ref: ${{ github.ref }}
