name: NPM

on: 
  workflow_dispatch:
    inputs:
      tag:
        description: Tag to publish
        required: true
        default: '*'

defaults:
  run:
    shell: bash

env:
  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

jobs:
  npm:
    name: Publish to NPM
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.CI_TOKEN }}

      - name: Setup PNPM
        uses: pnpm/action-setup@v2

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: 'https://registry.npmjs.org'
          cache: 'pnpm'

      - name: Get Tag
        id: get_tag
        run: echo "tag=$(git describe --tags --match="${{ github.event.inputs.tag }}" --abbrev=0)" >> $GITHUB_OUTPUT

      - name: Reset to Tag
        run: git reset --hard ${{ steps.get_tag.outputs.tag }}

      - name: Install Dependencies
        run: pnpm install
  
      - name: Publish
        run: |
          pkg_name=$(cut -d '@' -f1 <<< '${{ steps.get_tag.outputs.tag }}')
          pnpm publish --filter $pkg_name --no-git-checks
