name: Release

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Release / Pull Request
        uses: google-github-actions/release-please-action@v3
        id: release
        with:
          release-type: node
          command: manifest
          bootstrap-sha: 557d004bab2f5c9b95500b398a9a9d0518ef3e06
          last-release-sha: 557d004bab2f5c9b95500b398a9a9d0518ef3e06
      
      - uses: actions/checkout@v3
        if: ${{ steps.release.outputs.releases_created }}

      - name: Dispatch NPM
        if: ${{ steps.release.outputs.releases_created }}
        run: gh workflow run NPM -f tag=${{ steps.release.outputs.tag_name }}
        env:
          GH_TOKEN: ${{ secrets.CI_TOKEN }}
