name: Release

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Release / Pull Request
        uses: google-github-actions/release-please-action@v3
        id: release
        with:
          release-type: node
          command: manifest
      
      - uses: actions/checkout@v3
        if: ${{ steps.release.outputs.releases_created }}
        with:
          token: ${{ secrets.CI_TOKEN }}

      - name: Dispatch NPM
        if: ${{ steps.release.outputs.releases_created }}
        run: |
          echo "Using tag ${{ steps.release.outputs.tag_name }}"
          gh workflow run NPM -f tag=${{ steps.release.outputs.tag_name }}
        env:
          GH_TOKEN: ${{ secrets.CI_TOKEN }}
